name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Docker build
	  run: |
      docker login -u ${{ secrets.USERNAME }} -p ${{ secrets.PASSWORD }}
      docker build --platform linux/amd64 -t node-example .
      docker tag node-example rheech22/node-example:${GITHUB_SHA::7}
      docker push rheech22/node-example:${GITHUB_SHA::7}